companies = [
    # (sector, company name)
    ("Industrials", "3M"),
    ("Industrials", "A. O. Smith"),
    ("Health Care", "Abbott Laboratories"),
    ("Health Care", "AbbVie"),
    ("Information Technology", "Accenture"),
    ("Information Technology", "Adobe Inc."),
    ("Information Technology", "Advanced Micro Devices"),
    ("Utilities", "AES Corporation"),
    ("Financials", "Aflac"),
    ("Health Care", "Agilent Technologies"),
    ("Materials", "Air Products and Chemicals"),
    ("Consumer Discretionary", "Airbnb"),
    ("Information Technology", "Akamai Technologies"),
    ("Materials", "Albemarle Corporation"),
    ("Real Estate", "Alexandria Real Estate Equities"),
    ("Health Care", "Align Technology"),
    ("Industrials", "Allegion"),
    ("Utilities", "Alliant Energy"),
    ("Financials", "Allstate"),
    ("Communication Services", "Alphabet Inc. (Class A)"),
    ("Communication Services", "Alphabet Inc. (Class C)"),
    ("Consumer Staples", "Altria"),
    ("Consumer Discretionary", "Amazon"),
    ("Materials", "Amcor"),
    ("Utilities", "Ameren"),
    ("Industrials", "American Airlines Group"),
    ("Utilities", "American Electric Power"),
    ("Financials", "American Express"),
    ("Financials", "American International Group"),
    ("Real Estate", "American Tower"),
    ("Utilities", "American Water Works"),
    ("Financials", "Ameriprise Financial"),
    ("Industrials", "Ametek"),
    ("Health Care", "Amgen"),
    ("Information Technology", "Amphenol"),
    ("Information Technology", "Analog Devices"),
    ("Information Technology", "Ansys"),
    ("Financials", "Aon"),
    ("Energy", "APA Corporation"),
    ("Information Technology", "Apple Inc."),
    ("Information Technology", "Applied Materials"),
    ("Consumer Discretionary", "Aptiv"),
    ("Financials", "Arch Capital Group"),
    ("Consumer Staples", "Archer Daniels Midland"),
    ("Information Technology", "Arista Networks"),
    ("Financials", "Arthur J. Gallagher & Co."),
    ("Financials", "Assurant"),
    ("Communication Services", "AT&T"),
    ("Utilities", "Atmos Energy"),
    ("Information Technology", "Autodesk"),
    ("Industrials", "Automatic Data Processing"),
    ("Consumer Discretionary", "AutoZone"),
    ("Real Estate", "AvalonBay Communities"),
    ("Materials", "Avery Dennison"),
    ("Industrials", "Axon Enterprise"),
    ("Energy", "Baker Hughes"),
    ("Materials", "Ball Corporation"),
    ("Financials", "Bank of America"),
    ("Financials", "Bank of New York Mellon"),
    ("Consumer Discretionary", "Bath & Body Works, Inc."),
    ("Health Care", "Baxter International"),
    ("Health Care", "Becton Dickinson"),
    ("Financials", "Berkshire Hathaway"),
    ("Consumer Discretionary", "Best Buy"),
    ("Health Care", "Bio-Rad"),
    ("Health Care", "Bio-Techne"),
    ("Health Care", "Biogen"),
    ("Financials", "BlackRock"),
    ("Financials", "Blackstone"),
    ("Industrials", "Boeing"),
    ("Consumer Discretionary", "Booking Holdings"),
    ("Consumer Discretionary", "BorgWarner"),
    ("Health Care", "Boston Scientific"),
    ("Health Care", "Bristol Myers Squibb"),
    ("Information Technology", "Broadcom"),
    ("Industrials", "Broadridge Financial Solutions"),
    ("Financials", "Brown & Brown"),
    ("Consumer Staples", "Brown–Forman"),
    ("Industrials", "Builders FirstSource"),
    ("Consumer Staples", "Bunge Global SA"),
    ("Real Estate", "BXP, Inc."),
    ("Information Technology", "Cadence Design Systems"),
    ("Consumer Discretionary", "Caesars Entertainment"),
    ("Real Estate", "Camden Property Trust"),
    ("Consumer Staples", "Campbell Soup Company"),
    ("Financials", "Capital One"),
    ("Health Care", "Cardinal Health"),
    ("Consumer Discretionary", "CarMax"),
    ("Consumer Discretionary", "Carnival"),
    ("Industrials", "Carrier Global"),
    ("Health Care", "Catalent"),
    ("Industrials", "Caterpillar Inc."),
    ("Financials", "Cboe Global Markets"),
    ("Real Estate", "CBRE Group"),
    ("Information Technology", "CDW"),
    ("Materials", "Celanese"),
    ("Health Care", "Cencora"),
    ("Health Care", "Centene Corporation"),
    ("Utilities", "CenterPoint Energy"),
    ("Materials", "CF Industries"),
    ("Industrials", "CH Robinson"),
    ("Health Care", "Charles River Laboratories"),
    ("Financials", "Charles Schwab Corporation"),
    ("Communication Services", "Charter Communications"),
    ("Energy", "Chevron Corporation"),
    ("Consumer Discretionary", "Chipotle Mexican Grill"),
    ("Financials", "Chubb Limited"),
    ("Consumer Staples", "Church & Dwight"),
    ("Health Care", "Cigna"),
    ("Financials", "Cincinnati Financial"),
    ("Industrials", "Cintas"),
    ("Information Technology", "Cisco"),
    ("Financials", "Citigroup"),
    ("Financials", "Citizens Financial Group"),
    ("Consumer Staples", "Clorox"),
    ("Financials", "CME Group"),
    ("Utilities", "CMS Energy"),
    ("Consumer Staples", "Coca-Cola Company (The)"),
    ("Information Technology", "Cognizant"),
    ("Consumer Staples", "Colgate-Palmolive"),
    ("Communication Services", "Comcast"),
    ("Consumer Staples", "Conagra Brands"),
    ("Energy", "ConocoPhillips"),
    ("Utilities", "Consolidated Edison"),
    ("Consumer Staples", "Constellation Brands"),
    ("Utilities", "Constellation Energy"),
    ("Health Care", "Cooper Companies (The)"),
    ("Industrials", "Copart"),
    ("Information Technology", "Corning Inc."),
    ("Financials", "Corpay"),
    ("Materials", "Corteva"),
    ("Real Estate", "CoStar Group"),
    ("Consumer Staples", "Costco"),
    ("Energy", "Coterra"),
    ("Information Technology", "CrowdStrike"),
    ("Real Estate", "Crown Castle"),
    ("Industrials", "CSX"),
    ("Industrials", "Cummins"),
    ("Health Care", "CVS Health"),
    ("Health Care", "Danaher Corporation"),
    ("Consumer Discretionary", "Darden Restaurants"),
    ("Health Care", "DaVita"),
    ("Industrials", "Dayforce"),
    ("Consumer Discretionary", "Deckers Brands"),
    ("Industrials", "Deere & Company"),
    ("Industrials", "Delta Air Lines"),
    ("Energy", "Devon Energy"),
    ("Health Care", "Dexcom"),
    ("Energy", "Diamondback Energy"),
    ("Real Estate", "Digital Realty"),
    ("Financials", "Discover Financial"),
    ("Consumer Staples", "Dollar General"),
    ("Consumer Staples", "Dollar Tree"),
    ("Utilities", "Dominion Energy"),
    ("Consumer Discretionary", "Domino's"),
    ("Industrials", "Dover Corporation"),
    ("Materials", "Dow Inc."),
    ("Consumer Discretionary", "DR Horton"),
    ("Utilities", "DTE Energy"),
    ("Utilities", "Duke Energy"),
    ("Materials", "DuPont"),
    ("Materials", "Eastman Chemical Company"),
    ("Industrials", "Eaton Corporation"),
    ("Consumer Discretionary", "eBay"),
    ("Materials", "Ecolab"),
    ("Utilities", "Edison International"),
    ("Health Care", "Edwards Lifesciences"),
    ("Communication Services", "Electronic Arts"),
    ("Health Care", "Elevance Health"),
    ("Industrials", "Emerson Electric"),
    ("Information Technology", "Enphase"),
    ("Utilities", "Entergy"),
    ("Energy", "EOG Resources"),
    ("Information Technology", "EPAM Systems"),
    ("Energy", "EQT Corporation"),
    ("Industrials", "Equifax"),
    ("Real Estate", "Equinix"),
    ("Real Estate", "Equity Residential"),
    ("Real Estate", "Essex Property Trust"),
    ("Consumer Staples", "Estée Lauder Companies (The)"),
    ("Consumer Discretionary", "Etsy"),
    ("Financials", "Everest Re"),
    ("Utilities", "Evergy"),
    ("Utilities", "Eversource"),
    ("Utilities", "Exelon"),
    ("Consumer Discretionary", "Expedia Group"),
    ("Industrials", "Expeditors International"),
    ("Real Estate", "Extra Space Storage"),
    ("Energy", "ExxonMobil"),
    ("Information Technology", "F5, Inc."),
    ("Financials", "FactSet"),
    ("Information Technology", "Fair Isaac"),
    ("Industrials", "Fastenal"),
    ("Real Estate", "Federal Realty"),
    ("Industrials", "FedEx"),
    ("Financials", "Fidelity National Information Services"),
    ("Financials", "Fifth Third Bank"),
    ("Information Technology", "First Solar"),
    ("Utilities", "FirstEnergy"),
    ("Financials", "Fiserv"),
    ("Materials", "FMC Corporation"),
    ("Consumer Discretionary", "Ford Motor Company"),
    ("Information Technology", "Fortinet"),
    ("Industrials", "Fortive"),
    ("Communication Services", "Fox Corporation (Class A)"),
    ("Communication Services", "Fox Corporation (Class B)"),
    ("Financials", "Franklin Templeton"),
    ("Materials", "Freeport-McMoRan"),
    ("Consumer Discretionary", "Garmin"),
    ("Information Technology", "Gartner"),
    ("Industrials", "GE Aerospace"),
    ("Health Care", "GE HealthCare"),
    ("Industrials", "GE Vernova"),
    ("Information Technology", "Gen Digital"),
    ("Industrials", "Generac"),
    ("Industrials", "General Dynamics"),
    ("Consumer Staples", "General Mills"),
    ("Consumer Discretionary", "General Motors"),
    ("Consumer Discretionary", "Genuine Parts Company"),
    ("Health Care", "Gilead Sciences"),
    ("Financials", "Global Payments"),
    ("Financials", "Globe Life"),
    ("Information Technology", "GoDaddy"),
    ("Financials", "Goldman Sachs"),
    ("Energy", "Halliburton"),
    ("Financials", "Hartford (The)"),
    ("Consumer Discretionary", "Hasbro"),
    ("Health Care", "HCA Healthcare"),
    ("Real Estate", "Healthpeak"),
    ("Health Care", "Henry Schein"),
    ("Consumer Staples", "Hershey's"),
    ("Energy", "Hess Corporation"),
    ("Information Technology", "Hewlett Packard Enterprise"),
    ("Consumer Discretionary", "Hilton Worldwide"),
    ("Health Care", "Hologic"),
    ("Consumer Discretionary", "Home Depot (The)"),
    ("Industrials", "Honeywell"),
    ("Consumer Staples", "Hormel Foods"),
    ("Real Estate", "Host Hotels & Resorts"),
    ("Industrials", "Howmet Aerospace"),
    ("Information Technology", "HP Inc."),
    ("Industrials", "Hubbell Incorporated"),
    ("Health Care", "Humana"),
    ("Financials", "Huntington Bancshares"),
    ("Industrials", "Huntington Ingalls Industries"),
    ("Information Technology", "IBM"),
    ("Industrials", "IDEX Corporation"),
    ("Health Care", "Idexx Laboratories"),
    ("Industrials", "Illinois Tool Works"),
    ("Health Care", "Incyte"),
    ("Industrials", "Ingersoll Rand"),
    ("Health Care", "Insulet Corporation"),
    ("Information Technology", "Intel"),
    ("Financials", "Intercontinental Exchange"),
    ("Materials", "International Flavors & Fragrances"),
    ("Materials", "International Paper"),
    ("Communication Services", "Interpublic Group of Companies (The)"),
    ("Information Technology", "Intuit"),
    ("Health Care", "Intuitive Surgical"),
    ("Financials", "Invesco"),
    ("Real Estate", "Invitation Homes"),
    ("Health Care", "IQVIA"),
    ("Real Estate", "Iron Mountain"),
    ("Industrials", "J.B. Hunt"),
    ("Information Technology", "Jabil"),
    ("Financials", "Jack Henry & Associates"),
    ("Industrials", "Jacobs Solutions"),
    ("Health Care", "Johnson & Johnson"),
    ("Industrials", "Johnson Controls"),
    ("Financials", "JPMorgan Chase"),
    ("Information Technology", "Juniper Networks"),
    ("Consumer Staples", "Kellanova"),
    ("Consumer Staples", "Kenvue"),
    ("Consumer Staples", "Keurig Dr Pepper"),
    ("Financials", "KeyCorp"),
    ("Information Technology", "Keysight"),
    ("Consumer Staples", "Kimberly-Clark"),
    ("Real Estate", "Kimco Realty"),
    ("Energy", "Kinder Morgan"),
    ("Financials", "KKR"),
    ("Information Technology", "KLA Corporation"),
    ("Consumer Staples", "Kraft Heinz"),
    ("Consumer Staples", "Kroger"),
    ("Industrials", "L3Harris"),
    ("Health Care", "LabCorp"),
    ("Information Technology", "Lam Research"),
    ("Consumer Staples", "Lamb Weston"),
    ("Consumer Discretionary", "Las Vegas Sands"),
    ("Industrials", "Leidos"),
    ("Consumer Discretionary", "Lennar"),
    ("Health Care", "Lilly (Eli)"),
    ("Materials", "Linde plc"),
    ("Communication Services", "Live Nation Entertainment"),
    ("Consumer Discretionary", "LKQ Corporation"),
    ("Industrials", "Lockheed Martin"),
    ("Financials", "Loews Corporation"),
    ("Consumer Discretionary", "Lowe's"),
    ("Consumer Discretionary", "Lululemon Athletica"),
    ("Materials", "LyondellBasell"),
    ("Financials", "M&T Bank"),
    ("Energy", "Marathon Oil"),
    ("Energy", "Marathon Petroleum"),
    ("Financials", "MarketAxess"),
    ("Consumer Discretionary", "Marriott International"),
    ("Financials", "Marsh McLennan"),
    ("Materials", "Martin Marietta Materials"),
    ("Industrials", "Masco"),
    ("Financials", "Mastercard"),
    ("Communication Services", "Match Group"),
    ("Consumer Staples", "McCormick & Company"),
    ("Consumer Discretionary", "McDonald's"),
    ("Health Care", "McKesson Corporation"),
    ("Health Care", "Medtronic"),
    ("Health Care", "Merck & Co."),
    ("Communication Services", "Meta Platforms"),
    ("Financials", "MetLife"),
    ("Health Care", "Mettler Toledo"),
    ("Consumer Discretionary", "MGM Resorts"),
    ("Information Technology", "Microchip Technology"),
    ("Information Technology", "Micron Technology"),
    ("Information Technology", "Microsoft"),
    ("Real Estate", "Mid-America Apartment Communities"),
    ("Health Care", "Moderna"),
    ("Consumer Discretionary", "Mohawk Industries"),
    ("Health Care", "Molina Healthcare"),
    ("Consumer Staples", "Molson Coors Beverage Company"),
    ("Consumer Staples", "Mondelez International"),
    ("Information Technology", "Monolithic Power Systems"),
    ("Consumer Staples", "Monster Beverage"),
    ("Financials", "Moody's Corporation"),
    ("Financials", "Morgan Stanley"),
    ("Materials", "Mosaic Company (The)"),
    ("Information Technology", "Motorola Solutions"),
    ("Financials", "MSCI"),
    ("Financials", "Nasdaq, Inc."),
    ("Information Technology", "NetApp"),
    ("Communication Services", "Netflix"),
    ("Materials", "Newmont"),
    ("Communication Services", "News Corp (Class A)"),
    ("Communication Services", "News Corp (Class B)"),
    ("Utilities", "NextEra Energy"),
    ("Consumer Discretionary", "Nike, Inc."),
    ("Utilities", "NiSource"),
    ("Industrials", "Nordson Corporation"),
    ("Industrials", "Norfolk Southern Railway"),
    ("Financials", "Northern Trust"),
    ("Industrials", "Northrop Grumman"),
    ("Consumer Discretionary", "Norwegian Cruise Line Holdings"),
    ("Utilities", "NRG Energy"),
    ("Materials", "Nucor"),
    ("Information Technology", "Nvidia"),
    ("Consumer Discretionary", "NVR, Inc."),
    ("Information Technology", "NXP Semiconductors"),
    ("Consumer Discretionary", "O'Reilly Auto Parts"),
    ("Energy", "Occidental Petroleum"),
    ("Industrials", "Old Dominion"),
    ("Communication Services", "Omnicom Group"),
    ("Information Technology", "ON Semiconductor"),
    ("Energy", "ONEOK"),
    ("Information Technology", "Oracle Corporation"),
    ("Industrials", "Otis Worldwide"),
    ("Industrials", "Paccar"),
    ("Materials", "Packaging Corporation of America"),
    ("Information Technology", "Palo Alto Networks"),
    ("Communication Services", "Paramount Global"),
    ("Industrials", "Parker Hannifin"),
    ("Industrials", "Paychex"),
    ("Industrials", "Paycom"),
    ("Financials", "PayPal"),
    ("Industrials", "Pentair"),
    ("Consumer Staples", "PepsiCo"),
    ("Health Care", "Pfizer"),
    ("Utilities", "PG&E Corporation"),
    ("Consumer Staples", "Philip Morris International"),
    ("Energy", "Phillips 66"),
    ("Utilities", "Pinnacle West"),
    ("Financials", "PNC Financial Services"),
    ("Consumer Discretionary", "Pool Corporation"),
    ("Materials", "PPG Industries"),
    ("Utilities", "PPL Corporation"),
    ("Financials", "Principal Financial Group"),
    ("Consumer Staples", "Procter & Gamble"),
    ("Financials", "Progressive Corporation"),
    ("Real Estate", "Prologis"),
    ("Financials", "Prudential Financial"),
    ("Utilities", "Public Service Enterprise Group"),
    ("Information Technology", "PTC"),
    ("Real Estate", "Public Storage"),
    ("Consumer Discretionary", "PulteGroup"),
    ("Information Technology", "Qorvo"),
    ("Industrials", "Quanta Services"),
    ("Information Technology", "Qualcomm"),
    ("Health Care", "Quest Diagnostics"),
    ("Consumer Discretionary", "Ralph Lauren Corporation"),
    ("Financials", "Raymond James"),
    ("Industrials", "RTX Corporation"),
    ("Real Estate", "Realty Income"),
    ("Real Estate", "Regency Centers"),
    ("Health Care", "Regeneron"),
    ("Financials", "Regions Financial Corporation"),
    ("Industrials", "Republic Services"),
    ("Health Care", "ResMed"),
    ("Health Care", "Revvity"),
    ("Industrials", "Rockwell Automation"),
    ("Industrials", "Rollins, Inc."),
    ("Information Technology", "Roper Technologies"),
    ("Consumer Discretionary", "Ross Stores"),
    ("Consumer Discretionary", "Royal Caribbean Group"),
    ("Financials", "S&P Global"),
    ("Information Technology", "Salesforce"),
    ("Real Estate", "SBA Communications"),
    ("Energy", "Schlumberger"),
    ("Information Technology", "Seagate Technology"),
    ("Utilities", "Sempra Energy"),
    ("Information Technology", "ServiceNow"),
    ("Materials", "Sherwin-Williams"),
    ("Real Estate", "Simon Property Group"),
    ("Information Technology", "Skyworks Solutions"),
    ("Consumer Staples", "J.M. Smucker Company (The)"),
    ("Materials", "Smurfit WestRock"),
    ("Industrials", "Snap-on"),
    ("Health Care", "Solventum"),
    ("Utilities", "Southern Company"),
    ("Industrials", "Southwest Airlines"),
    ("Industrials", "Stanley Black & Decker"),
    ("Consumer Discretionary", "Starbucks"),
    ("Financials", "State Street Corporation"),
    ("Materials", "Steel Dynamics"),
    ("Health Care", "Steris"),
    ("Health Care", "Stryker Corporation"),
    ("Information Technology", "Supermicro"),
    ("Financials", "Synchrony Financial"),
    ("Information Technology", "Synopsys"),
    ("Consumer Staples", "Sysco"),
    ("Communication Services", "T-Mobile US"),
    ("Financials", "T. Rowe Price"),
    ("Communication Services", "Take-Two Interactive"),
    ("Consumer Discretionary", "Tapestry, Inc."),
    ("Energy", "Targa Resources"),
    ("Consumer Staples", "Target Corporation"),
    ("Information Technology", "TE Connectivity"),
    ("Information Technology", "Teledyne Technologies"),
    ("Health Care", "Teleflex"),
    ("Information Technology", "Teradyne"),
    ("Consumer Discretionary", "Tesla, Inc."),
    ("Information Technology", "Texas Instruments"),
    ("Industrials", "Textron"),
    ("Health Care", "Thermo Fisher Scientific"),
    ("Consumer Discretionary", "TJX Companies"),
    ("Consumer Discretionary", "Tractor Supply"),
    ("Industrials", "Trane Technologies"),
    ("Industrials", "TransDigm Group"),
    ("Financials", "Travelers Companies (The)"),
    ("Information Technology", "Trimble Inc."),
    ("Financials", "Truist"),
    ("Information Technology", "Tyler Technologies"),
    ("Consumer Staples", "Tyson Foods"),
    ("Financials", "U.S. Bank"),
    ("Industrials", "Uber"),
    ("Real Estate", "UDR, Inc."),
    ("Consumer Discretionary", "Ulta Beauty"),
    ("Industrials", "Union Pacific Corporation"),
    ("Industrials", "United Airlines Holdings"),
    ("Industrials", "United Parcel Service"),
    ("Industrials", "United Rentals"),
    ("Health Care", "UnitedHealth Group"),
    ("Health Care", "Universal Health Services"),
    ("Energy", "Valero Energy"),
    ("Real Estate", "Ventas"),
    ("Industrials", "Veralto"),
    ("Information Technology", "Verisign"),
    ("Industrials", "Verisk"),
    ("Communication Services", "Verizon"),
    ("Health Care", "Vertex Pharmaceuticals"),
    ("Health Care", "Viatris"),
    ("Real Estate", "Vici Properties"),
    ("Financials", "Visa Inc."),
    ("Utilities", "Vistra"),
    ("Materials", "Vulcan Materials Company"),
    ("Financials", "W. R. Berkley Corporation"),
    ("Industrials", "W. W. Grainger"),
    ("Industrials", "Wabtec"),
    ("Consumer Staples", "Walgreens Boots Alliance"),
    ("Consumer Staples", "Walmart"),
    ("Communication Services", "Walt Disney Company (The)"),
    ("Communication Services", "Warner Bros. Discovery"),
    ("Industrials", "Waste Management"),
    ("Health Care", "Waters Corporation"),
    ("Utilities", "WEC Energy Group"),
    ("Financials", "Wells Fargo"),
    ("Real Estate", "Welltower"),
    ("Health Care", "West Pharmaceutical Services"),
    ("Information Technology", "Western Digital"),
    ("Real Estate", "Weyerhaeuser"),
    ("Energy", "Williams Companies"),
    ("Financials", "Willis Towers Watson"),
    ("Consumer Discretionary", "Wynn Resorts"),
    ("Utilities", "Xcel Energy"),
    ("Industrials", "Xylem Inc."),
    ("Consumer Discretionary", "Yum! Brands"),
]
